FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Selectperson/Selectperson.csproj", "Selectperson/"]
RUN dotnet restore "Selectperson/Selectperson.csproj"
COPY . .
WORKDIR "/src/Selectperson"
RUN dotnet build "Selectperson.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Selectperson.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Selectperson.dll"]
